model_path: "yolov4.onnx"
sub_topic: "/kitti/image/color/left"
pub_topic: "bboxes"
subscribed_type: "Image"
model_input_type: "Image"
preprocessing_steps:    
  - name: type_conv_image_to_numpy
    params:    
  - name: image_resize_and_scale
    params:
      - name: target_size
        value: !!python/tuple [416,416]  
      - name: padding
        value: False
  - name: array_to_contigous_array
    params:


model_output_type: "Image"
publish_type: "Image"
postprocessing_steps:
  - name: image_define_anchor_boxes
    params: 
      - name: anchors
        value: [[[12, 16],[19, 36],[40, 28]],[[ 36, 75],[76, 55],[72, 146]],[[142, 110],[192, 243],[459, 401]]]
      - name: strides
        value: [8, 16, 32]
      - name: xyscale
        value: [1.2, 1.1, 1.05]
  - name: image_remove_low_prob_boxes
    params:
      - name: org_img_shape
        value: [512,1392]
      - name: input_size
        value: [416,416]
      - name: score_threshold
        value: 0.25
  - name: image_non_maximum_suppression
    params:
      - name: iou_threshold
        value: 0.213
  - name: image_draw_bboxes_to_image
    params:
      - name: orig_image
        use_orig_input: True
      - name: classes
        value: ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat","traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat","dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack","umbrella", "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball","kite", "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket","bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple","sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair","sofa", "potted plant", "bed", "dining table", "toilet", "tvmonitor", "laptop", "mouse","remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink", "refrigerator","book", "clock", "vase", "scissors", "teddy bear", "hair drier", "toothbrush"]
  - name: type_conv_numpy_to_image
    params:  
        


    
      
