model_path: "FasterRCNN-10.onnx"
pub_topic: "bboxes"
sub_topics: 
  - topic: /image/demo
    subscribed_type: Image
    modelInputPosition: 0
    preprocessing_steps:     
      - name: type_conv_image_to_numpy
        params:   
      - name: image_resize_by_ratio
        params:
          - name: ratio
            value: 800.00
      - name: array_transpose_to_shape
        params:      
          - name: transpose_order
            value: !!python/tuple [2,0,1]                      
      - name: image_pad_image
        params:
          - name: pad_value
            value: 32
      - name: image_subtract_mean_vec
        params:
          - name: mean
            value: [102.9801, 115.9465, 122.7717]


model_output_type: "Image"
publish_type: "Image"

postprocessing_steps:
  # - name: toDetection2DArray
  #   params:
  #     - name: data
  #       use_orig_input_pos: [0]
  #     - name: boxes
  #       get_from_output_pos: [0]
  #     - name: labels
  #       get_from_output_pos: [1]
  #     - name: scores
  #       get_from_output_pos: [2]
  - name: type_conv_image_to_numpy
    params:
      - name: data
        use_orig_input_pos: [0]
  - name: image_draw_bounding_boxes
    params: 
      - name: boxes
        get_from_output_pos: [0]
      - name: labels
        get_from_output_pos: [1]
      - name: scores
        get_from_output_pos: [2]
      - name: classes
        value: ["__background", "person", "bicycle", "car", "motorcycle", "airplane","bus", "train", "truck", "boat", "traffic light", "fire hydrant","stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse","sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack","umbrella", "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard","sports ball", "kite", "baseball bat", "baseball glove", "skateboard","surfboard", "tennis racket", "bottle", "wine glass", "cup", "fork","knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange","broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair","couch", "potted plant", "bed", "dining table", "toilet", "tv", "laptop","mouse", "remote", "keyboard", "cell phone", "microwave", "oven","toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors","teddy bear", "hair drier", "toothbrush"]
      - name: scale_boxes_by_ratio
        value: 800.00
      - name: score_threshold
        value: 0.8  
  - name: type_conv_numpy_to_image
    params:  
        


    
      
